
version: "3"
services:
  registry:
    build:
      context: ${PROJECT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/registry/Dockerfile
    ports:
      - "2020:2020"
    networks:
      - my_network
    cap_add:
      - NET_ADMIN

  node1:
    build:
      context: ${PROJECT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/node/Dockerfile
    privileged: true
    ports:
      - "8001:8001"
    environment:
      - NODE_ID=node1
    networks:
      - my_network
    depends_on:
      - registry
    cap_add:
      - NET_ADMIN

  node2:
    build:
      context: ${PROJECT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/node/Dockerfile
    privileged: true
    ports:
      - "8002:8002"
    environment:
      - NODE_ID=node2
    networks:
      - my_network
    depends_on:
      - registry
    cap_add:
      - NET_ADMIN

  node3:
    build:
      context: ${PROJECT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/node/Dockerfile
    privileged: true
    ports:
      - "8003:8003"
    environment:
      - NODE_ID=node3
    networks:
      - my_network
    depends_on:
      - registry
    cap_add:
      - NET_ADMIN

  node4:
    build:
      context: ${PROJECT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/node/Dockerfile
    privileged: true
    ports:
      - "8004:8004"
    environment:
      - NODE_ID=node4
    networks:
      - my_network
    depends_on:
      - registry
    cap_add:
      - NET_ADMIN

networks:
  my_network:
    driver: bridge
